import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "@insaeng/design-system/fonts.css";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pochaevsk = localFont({
  src: "../../../packages/design-system/assets/fonts/Pochaevsk-Regular.woff2",
  variable: "--font-pochaevsk",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Jaewon Yang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`
        ${geistMono.variable}
        ${pochaevsk.variable}
        h-full antialiased
      `}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
